### ISSUE TITLE
Deno Crate Organization

### ISSUE THREAD

**Issue by ajcwebdev** [ParisDeno/talks#10]
# Talk proposal - Paris Deno

## Talk description
* Title: **Deno Crate Organization**
* Content: Unlike Node, which is a monolithic project, Deno is organized into a collection of [Rust crates](https://crates.io/). I will summarize the history of why Ryan Dhal made this choice and what each crate is for. These include:
  * `deno` - Deno executable
  * `deno_core` - Ops and Resources
  * `rusty_v8` Rust interface to V8
  * `deno_typescript` - type-checking and type-stripping at compile-time

* Duration:
  - [ ] 5 minutes (Lightning talk)
  - [ ] 10 minutes
  - [ ] 20 minutes
  - [x] 30 minutes
  - [ ] Other, please specify:
* Level:
  - [ ] Beginner
  - [x] Intermediate
  - [ ] Advanced

## About you
* Name: Anthony Campolo
* Twitter: https://twitter.com/ajcwebdev
* Company: ajcwebdev

**Comment by lsagetlethias** [comment]
Thank you a lot for your proposal. It's great because it's in the same theme than #9 👍

**Comment by bartlomieju** [comment]
@ajcwebdev very nice! I'm a bit afraid we might be discussing similar stuff. Maybe we could switch order of the talks to give viewers overview of "current" architecture (your talk) and "upcoming" changes to it (my talk)?

**Comment by ajcwebdev** [comment]
That's fine with me, I was planning on talking a good deal about the history so it can be a bit of a "Past, Present, Future" across both talks.

**Comment by bartlomieju** [comment]
> That's fine with me, I was planning on talking a good deal about the history so it can be a bit of a "Past, Present, Future" across both talks.

@ajcwebdev that sounds great! Looking forward!

**Comment by lsagetlethias** [comment]
Just to confirm with you guys, first talk is @ajcwebdev 's one, then @bartlomieju , right ? 😅

**Comment by bartlomieju** [comment]
@lsagetlethias yes, I think so 👍

**Comment by ajcwebdev** [comment]
Yup! And just to double check, I'm at MDT, so is 7:00 GMT+2 going to be 11:00am my time or 10:00am? I plugged it into a conversion and it came out 11:00am, but when I added the event to my google calendar it came out as 10:00am, so I'm a little confused lol.

**Comment by lsagetlethias** [comment]
@ajcwebdev I will send a dm on twitter with all the information but AFAIK:
![image](https://user-images.githubusercontent.com/5783789/95206418-f89f6400-07e6-11eb-9f62-312153bbcfec.png)
