### ISSUE TITLE
Unit tests in deno : A std journey

### ISSUE THREAD

**Issue by paulsouche** [ParisDeno/talks#3]
# Talk proposal - Paris Deno

## Talk description
* Title:  Unit tests in deno : A std journey
* Content : In this presentation we will see how to use the cli to run unit tests in deno, write assertions and have an overview of the benchmark API.
* Duration:
  - [ ] 5 minutes (Lightning talk)
  - [X] 10 minutes
  - [ ] 20 minutes
  - [ ] 30 minutes
  - [ ] Other, please specify:
* Level:
  - [x] Beginner
  - [ ] Intermediate
  - [ ] Advanced

## About you
* Name: Paul SOUCHE
* Twitter: @paulsouche
* Company: Paris TypeScript

**Comment by venikman** [comment]
will you record talk? and will it be in French or English?

**Comment by lsagetlethias** [comment]
This talk and the whole session will be livestreamed, recorded, and in English
