### ISSUE TITLE
How to get your npm package ready for Deno, CommonJS and ES Modules all together?

### ISSUE THREAD

**Issue by dubzzz** [ParisDeno/talks#5]
# Talk proposal - Paris Deno

## Talk description
* Title: How to get your npm package ready for Deno, CommonJS and ES Modules all together?
* Content (Briefly describe the content of the presentation): The JavaScript/TypeScript eco-system has never been so fragmented. On the one hand, Node is just adopting ES Modules but does it with no real backward compatibility. It does not even follow what bundlers have been doing so far. On the other hand, Deno has its own way to write TypeScript and publish packages. In addition to that, if your package is providing typings you want not to break backward compatibity each time you use new features offered by TypeScript. As a library maintainer, supporting correctly all of those _platforms_ without breaking bundlers or old versions has became a huge challenge. This talk will dive in those challenges by taking what has been done in [fast-check](https://github.com/dubzzz/fast-check/) to support that.
* Duration:
  - [ ] 5 minutes (Lightning talk)
  - [ ] 10 minutes
  - [x] 20 minutes
  - [ ] 30 minutes
  - [ ] Other, please specify:
* Level:
  - [ ] Beginner
  - [x] Intermediate
  - [ ] Advanced

## About you
* Name: Nicolas Dubien
* Twitter: [@ndubien](https://twitter.com/ndubien)
* Company: Pigment

**Comment by lsagetlethias** [comment]
@dubzzz Toujours partant pour le faire à la prochaine session  :D ?

**Comment by dubzzz** [comment]
Normalement oui, tu as la date du prochain meetup ?

**Comment by lsagetlethias** [comment]
02 juin !

**Comment by dubzzz** [comment]
Ok pour moi. D'ici là j'aurais le temps de faire des slides sur ce sujet ;)

**Comment by lsagetlethias** [comment]
Great, je te programme alors, merci encore 🙏

**Comment by dubzzz** [comment]
Merci ;)

**Comment by garronej** [comment]
Salue @dubzzz,
Je pense que c'est super que tu passes avant moi, ça aidera les gens à mieux comprendre ce que je raconte.  
Par contre, pour qu'il n'y ait pas trop de redite entre [ma présentation](https://github.com/ParisDeno/talks/issues/8) et la tienne ça serait super si tu pouvais me transmettre tes slides par avance, quand tu les auras terminés et si tu es d'accord bien sûr.  
Pour ma part tu peux te faire une idée très précise de ce que je vais raconter en consultant le readme de [Denoify](https://github.com/garronej/denoify)  

Salut :octocat:

**Comment by dubzzz** [comment]
Hello 👋,

Pour le moment je n'ai pas encore finalisé mes slides.

L'idée du talk serait :
1. Présentation de l'histoire de l'import (de require à import)
2. Comment être compatible cjs et esm à la fois
3. Et deno dans tout ça

Pour cette troisième partie, je vais surtout utiliser Pika et montrer que les paquets esm sont utilisables dans deno en passant par Pika. Je ne pense pas forcément pousser ce sujet trop trop loin de mon côté.

**Comment by garronej** [comment]
@dubzzz Super, merci !

**Comment by dubzzz** [comment]
@garronej So sorry for the delay, it took me a while to end the slides. Here they are: https://dubzzz.github.io/fast-check.github.com/talks/meetup-parisdeno-02062020/#/

As stated above the main subject is more about how to be compatible with CommonJS and ES Modules altogether. At the end, I open the discussion to Deno using Pika but it's far from being the nicest solution for Deno.

**Comment by garronej** [comment]
Wahoo great slides! What did you use to make them? Keynote? 
The fact that they are hosted on GitHub pages is cool as well.  
[Here](https://docs.google.com/presentation/d/1Mz-XvweF4398JhSbdaD0eNakuFWj_8S3aNCx4VnAMaM/edit?usp=sharing) are mines if you want to have a look.  
Thank you for sharing, see you this afternoon.

**Comment by dubzzz** [comment]
RevealJS for the slides. Another one pretty cool is mdx-deck + CodeSurfer.
