### ISSUE TITLE
Introduction to Drash

### ISSUE THREAD

**Issue by mhvsa** [ParisDeno/talks#6]
# Talk proposal - Paris Deno

## Talk description
* Title: Introduction to Drash
* Content: Let's explore one of the fresh REST web frameworks out there and build something useful with it!
* Duration:
  - [ ] 5 minutes (Lightning talk)
  - [ ] 10 minutes
  - [x] 20 minutes
  - [ ] 30 minutes
  - [ ] Other, please specify:
* Level:
  - [x] Beginner
  - [ ] Intermediate
  - [ ] Advanced

## About you
* Name: Michał Sabiniarz
* Twitter: https://twitter.com/michalsabiniarz
* Company: Straal

**Comment by crookse** [comment]
Drash has a new tutorial: https://drash.land/docs/#/advanced-tutorials/creating-a-docker-container/docker-compose-setup

🙂

**Comment by mhvsa** [comment]
Fantastic! Thank you, I'll use that
