### ISSUE TITLE
Power your frontend tooling with Deno

### ISSUE THREAD

**Issue by yacinehmito** [ParisDeno/talks#7]
# Talk proposal - Paris Deno

## Talk description
* Title: Power your frontend tooling with Deno
* Content: Starting a quick frontend project is nowadays very easy thanks to a large choice of boilerplate repos and bootstrapping tools. They have everything you need: TypeScript support, JSX, a test runner, bundling, etc... Still, they often require you to download thousands of dependencies and bring with them a lot of magic. In this talk we will see how to bootstrap a small frontend project with those same features using only Deno, and explore what this could mean for the future of frontend web development.
* Duration:
  - [ ] 5 minutes (Lightning talk)
  - [ ] 10 minutes
  - [x] 20 minutes (Can be lengthened/shortened depending on the need)
  - [ ] 30 minutes
  - [ ] Other, please specify:
* Level:
  - [x] Beginner
  - [ ] Intermediate
  - [ ] Advanced

The talk can be either in English or French, depending on the organisers' preferences.

## About you
* Name: Yacine Hmito
* Twitter: [yacinehmito](https://twitter.com/yacinehmito)
* Company: [Spendesk](https://www.welcometothejungle.com/en/companies/spendesk)

I have been following Deno since its announcement (just lurking though) and used it for a personal project. I am very excited for the v1 and can't wait to use it at scale.

I am particularly interested in how it can greatly simplify tooling, frontend and backend, as I have experienced how these can bog down large projects at Spendesk.

**Comment by David-Else** [comment]
@yacinehmito I loved your Deno talk! Could you share the code in your examples, and any possible updates that may have overcome the problems you discussed? 

I have noted that popular type definitions (inc React) have moved and been updated, and now live here https://deno.land/x/types/

**Comment by yacinehmito** [comment]
Hello @David-Else! Thank you very much for listening to the talk. 🤗

I plan on publishing an article with code and everything updated once Deno hits 1.0. 

In the meantime, I pushed in a repo what I worked with locally. I can't promise it still works, and it's pretty barebone: https://github.com/yacinehmito/deno-meetup
The branch `talk` has what we ended up with at the end of the talk. The branch `preparation` as some stuff I did before the talk; it probably doesn't work but goes a bit deeper.

If you are interested grab the code while you can because I am likely to delete the repository once the article is posted.

Cheers!

**Comment by David-Else** [comment]
@yacinehmito Thanks for the repo link! Looking forward to your article.

**Comment by David-Else** [comment]
Hello. Please respond here when it is out so I get a notification, looking forward to it, cheers!
