### ISSUE TITLE
Introducing Denoify, a build tool, that converts NPM modules into Deno modules.

### ISSUE THREAD

**Issue by garronej** [ParisDeno/talks#8]
# Talk proposal - Paris Deno

## Talk description
* Title: Introducing [Denoify](https://github.com/garronej/denoify), a build tool, that converts NPM modules into Deno modules.
* Content: 
Wouldn't it be great to have a tool able to make all the major NPM modules available to Deno?
Although it is quite easy to port a module, maintaining two codebases is a chore. Hence Denoify, a build tool aimed at NPM package authors that take as input a TypeScript codebase that was meant to target node and/or the web and spits out a modified version of the source files ready to be deployed as a Deno module.  
The built tools come hand in hand with a GitHub action CI setup that takes charge of publishing on both [deno.land/x](https://deno.land/x/) and NPM.  
During this talk, I will show what the tool is capable of today, what it could be capable of tomorrow, and the help it needs from the opensource community to get there.

* Duration:
  - [ ] 5 minutes (Lightning talk)
  - [ ] 10 minutes
  - [x] 20 minutes
  - [ ] 30 minutes
  - [ ] Other, please specify:
* Level:
  - [x] Beginner
  - [ ] Intermediate
  - [ ] Advanced

## About you
* Name: Joseph Garrone
* Twitter: [@GarroneJoseph](https://twitter.com/GarroneJoseph)
* Company: [Semasim](https://www.semasim.com)

PS: I hope you won't find the topic of this talk too close to the one of Nicolas Dubin. I think they can be complementary.

**Comment by lsagetlethias** [comment]
LGTM;

Thanks for the abstract. Doing it in english is ok for you?

**Comment by garronej** [comment]
> LGTM;
> 
> Thanks for the abstract. Doing it in english is ok for you?

Yes sure

**Comment by garronej** [comment]
Hey @bios21 @spontoreau 👋,
Is my proposal accepted? I don't see the label.

Many thanks

**Comment by lsagetlethias** [comment]
OMG, yes sorry, my bad. I put the milestone but forgot the label ...

**Comment by garronej** [comment]
No problem, thank you!
