### ISSUE TITLE
Deno internals - how modern JS/TS runtime is built

### ISSUE THREAD

**Issue by bartlomieju** [ParisDeno/talks#9]
# Talk proposal - Paris Deno

## Talk description
* Title: Deno internals - how modern JS/TS runtime is built
* Content (Briefly describe the content of the presentation): 
I gave this talk almost a year ago (https://www.youtube.com/watch?v=qt7fbmypAFk), but a loooot has changed since then. So I'd like to give you updated overview of the Deno architecture and where it's headed. 

* Duration:
  - [ ] 5 minutes (Lightning talk)
  - [ ] 10 minutes
  - [ ] 20 minutes
  - [x] 30 minutes
  - [ ] Other, please specify:
* Level:
  - [ ] Beginner
  - [x] Intermediate
  - [x] Advanced

## About you
* Name: Bartek Iwańczuk
* Twitter: @biwanczuk
* Company: @denoland

**Comment by bartlomieju** [comment]
I'm more than happy to focus on describing specific parts of the project according to community interest.

**Comment by lsagetlethias** [comment]
Thank you a lot for your talk! I'm really looking forward to see it 💯

**Comment by spontoreau** [comment]
Awesome 👍
